# **Differentiation Capabilities in Deepchem**

Author : Rakshit Kr Singh : [Website](https://greatrsingh.in/) : [LinkedIn](https://www.linkedin.com/in/rakshit-singh-ai/) : [GitHub](https://github.com/GreatRSingh)

# Methods for solving Non Linear Equations

<h5>
Nonlinear Equations (NLE):
Nonlinear equations are mathematical expressions where the relationship between the variables is not linear. Unlike linear equations, which have a constant rate of change, nonlinear equations involve terms with higher powers or functions like exponentials, logarithms, trigonometric functions, etc.

A simple NLE is y = x^2
<br>
<br>
Non-linear equations are essential across various disciplines, including physics, engineering, economics, biology, and finance. They describe complex relationships and phenomena that cannot be adequately modeled with linear equations. From gravitational interactions in celestial bodies to biochemical reactions in living organisms, non-linear equations play a vital role in understanding and predicting real-world systems. Whether it's optimizing structures, analyzing market dynamics, or designing machine learning algorithms, solving non-linear equations is fundamental for advancing scientific knowledge and technological innovation.
</h5>

## Broyden1 method

<h5>
Broyden's First Method, is an iterative numerical method used for solving systems of nonlinear equations. It's particularly useful when the Jacobian matrix (the matrix of partial derivatives of the equations) is difficult or expensive to compute. 
<br>
<br>
Broyden's Method is an extension of the Secant Method for systems of nonlinear equations. It iteratively updates an approximation to the Jacobian matrix using the information from previous iterations. The algorithm converges to the solution by updating the variables in the direction that minimizes the norm of the system of equations.
<br>
<br>
Advantages:

- Does not require explicit computation of the Jacobian matrix, which can be computationally expensive or difficult to obtain.
- Can converge to solutions even for systems with singular or ill-conditioned Jacobians.
- Suitable for large-scale systems of nonlinear equations.

Limitations:

- Convergence may be slower compared to methods that utilize the true Jacobian matrix.
- Convergence behavior may be sensitive to the choice of initial approximation to the Jacobian and the update formula.
<br>
<br>
$e^{i\pi}+1=0$

$$ \frac{1}{n}^n$$
</h5>

References

[1].. "A class of methods for solving nonlinear simultaneous equations" by Charles G. Broyden

In [15]:
import torch
from deepchem.utils.differentiation_utils import rootfinder
def func1(x, A):
    return x[0] * x[1] - A
y0 = torch.zeros((2, 1))
A = torch.tensor([10, 10])
yroot = rootfinder(func1, y0, params=(A,), method='broyden1')
yroot, func1(yroot, A)

(tensor([[-3.1623],
         [-3.1623]]),
 tensor([-9.5367e-07, -9.5367e-07]))

# Broyden2 Method

<h5>
The Broyden2 method is a specific variant within the Broyden family of methods.

The Broyden2 method is an algorithm used to find the root of a function.
It's a quasi-Newton method, which means it iteratively improves an
approximation of the function's Jacobian (the matrix that contains all its
first-order partial derivatives) to solve the system of equations where
the function itself is zero.
</h5>

In [2]:
import torch
from deepchem.utils.differentiation_utils import rootfinder
def func1(y, A):
    return torch.tanh(A @ y + 0.1) + y / 2.0
A = torch.tensor([[1.1, 0.4], [0.3, 0.8]]).requires_grad_()
y0 = torch.zeros((2,1))
yroot = rootfinder(func1, y0, params=(A,), method='broyden2')
yroot, func1(yroot, A)

(tensor([[-0.0459],
         [-0.0663]], grad_fn=<_RootFinderBackward>),
 tensor([[ 1.0300e-06],
         [-3.2783e-07]], grad_fn=<AddBackward0>))

# Minimizer

<h5>
Minimization algorithms, including variants of gradient descent like ADAM, are fundamental tools in various fields of science, engineering, and optimization. Here are some common usage scenarios and applications of minimization algorithms:
<br>

- Function Optimization: Minimization algorithms are used to find the minimum (or maximum) of a function. This is applicable in various contexts such as mathematical optimization, engineering design, finance (e.g., portfolio optimization), and physics (e.g., minimizing energy functions).

- Global Optimization: Minimization algorithms are employed in global optimization problems where the goal is to find the global minimum of a function within a given domain. Evolutionary algorithms, simulated annealing, and particle swarm optimization are examples of algorithms used for global optimization.

- Nonlinear Optimization: Minimization algorithms are crucial for solving nonlinear optimization problems, where the objective function or constraints are nonlinear. These problems arise in engineering design, process optimization, and operations research.

- Quantum Computing: Minimization algorithms play a role in quantum computing, particularly in quantum optimization and quantum machine learning. Quantum annealing and variational quantum algorithms are examples of techniques used for optimization tasks.

- Control Systems: Minimization algorithms are used in control systems engineering to optimize control strategies and parameters for achieving desired system behavior and performance.

These are just a few examples of the wide-ranging applications of minimization algorithms. They are essential tools for solving optimization problems in diverse fields, ranging from scientific research and engineering to finance and machine learning.
</h5>

## Gradient Descent (GD)

<h5>
Gradient descent is a method for unconstrained mathematical optimization. It is a first-order iterative algorithm for finding a local minimum of a differentiable multivariate function.
<br>
<br>
Gradient Descent is a fundamental optimization algorithm used to minimize the cost function in various machine learning and optimization problems. It iteratively updates the parameters in the direction of the negative gradient of the cost function.
</h5>

In [5]:
import torch
from deepchem.utils.differentiation_utils.optimize.minimizer import gd
def fcn(x):
    return 2 * x + (x - 2) ** 2, 2 * (x - 2) + 2
x0 = torch.tensor(0.0, requires_grad=True)
x = gd(fcn, x0, [])
x, fcn(x)

(tensor(0.9973), (tensor(3.0000), tensor(-0.0053)))

In [14]:
import torch
from deepchem.utils.differentiation_utils.optimize.minimizer import adam
def fcn(x):
    return 2 * x + (x - 2) ** 3, 2 * (x - 2)**2 + 2
x0 = torch.tensor(0.0, requires_grad=True)
x = adam(fcn, x0, [])
x, fcn(x)

(tensor(-1.1687), (tensor(-34.1530), tensor(22.0812)))