# **Differentiation Capabilities in Deepchem**

Author : Rakshit Kr Singh : [Website](https://greatrsingh.in/) : [LinkedIn](https://www.linkedin.com/in/rakshit-singh-ai/) : [GitHub](https://github.com/GreatRSingh)

# Methods for solving Non Linear Equations

<h4>
Non-linear equations are essential across various disciplines, including physics, engineering, economics, biology, and finance. They describe complex relationships and phenomena that cannot be adequately modeled with linear equations. From gravitational interactions in celestial bodies to biochemical reactions in living organisms, non-linear equations play a vital role in understanding and predicting real-world systems. Whether it's optimizing structures, analyzing market dynamics, or designing machine learning algorithms, solving non-linear equations is fundamental for advancing scientific knowledge and technological innovation.
</h4>

## Broyden1 method

<h5>
Find a root of a function, using Broyden’s first Jacobian approximation.
This method is also known as "Broyden’s good method".

The Broyden method is a numerical algorithm used to solve systems of nonlinear equations.
It's an iterative method that updates an approximation to the Jacobian matrix, which
represents the system's derivatives with respect to the variables. Instead of recalculating
the Jacobian matrix at each iteration, the Broyden method updates it using rank-one corrections.
</h5>

References

[1].. "A class of methods for solving nonlinear simultaneous equations" by Charles G. Broyden

In [15]:
import torch
from deepchem.utils.differentiation_utils import rootfinder
def func1(x, A):
    return x[0] * x[1] - A
y0 = torch.zeros((2, 1))
A = torch.tensor([10, 10])
yroot = rootfinder(func1, y0, params=(A,), method='broyden1')
yroot, func1(yroot, A)

(tensor([[-3.1623],
         [-3.1623]]),
 tensor([-9.5367e-07, -9.5367e-07]))

# Broyden2 Method

<h5>
The Broyden2 method is a specific variant within the Broyden family of methods.

The Broyden2 method is an algorithm used to find the root of a function.
It's a quasi-Newton method, which means it iteratively improves an
approximation of the function's Jacobian (the matrix that contains all its
first-order partial derivatives) to solve the system of equations where
the function itself is zero.
</h5>

In [2]:
import torch
from deepchem.utils.differentiation_utils import rootfinder
def func1(y, A):
    return torch.tanh(A @ y + 0.1) + y / 2.0
A = torch.tensor([[1.1, 0.4], [0.3, 0.8]]).requires_grad_()
y0 = torch.zeros((2,1))
yroot = rootfinder(func1, y0, params=(A,), method='broyden2')
yroot, func1(yroot, A)

(tensor([[-0.0459],
         [-0.0663]], grad_fn=<_RootFinderBackward>),
 tensor([[ 1.0300e-06],
         [-3.2783e-07]], grad_fn=<AddBackward0>))

# Minimizer

<h5>
Minimization algorithms, including variants of gradient descent like ADAM, are fundamental tools in various fields of science, engineering, and optimization. Here are some common usage scenarios and applications of minimization algorithms:
<br>

1. Function Optimization: Minimization algorithms are used to find the minimum (or maximum) of a function. This is applicable in various contexts such as mathematical optimization, engineering design, finance (e.g., portfolio optimization), and physics (e.g., minimizing energy functions).

2. Global Optimization: Minimization algorithms are employed in global optimization problems where the goal is to find the global minimum of a function within a given domain. Evolutionary algorithms, simulated annealing, and particle swarm optimization are examples of algorithms used for global optimization.

3. Nonlinear Optimization: Minimization algorithms are crucial for solving nonlinear optimization problems, where the objective function or constraints are nonlinear. These problems arise in engineering design, process optimization, and operations research.

4. Quantum Computing: Minimization algorithms play a role in quantum computing, particularly in quantum optimization and quantum machine learning. Quantum annealing and variational quantum algorithms are examples of techniques used for optimization tasks.

5. Control Systems: Minimization algorithms are used in control systems engineering to optimize control strategies and parameters for achieving desired system behavior and performance.

These are just a few examples of the wide-ranging applications of minimization algorithms. They are essential tools for solving optimization problems in diverse fields, ranging from scientific research and engineering to finance and machine learning.
</h5>

In [5]:
import torch
from deepchem.utils.differentiation_utils.optimize.minimizer import gd
def fcn(x):
    return 2 * x + (x - 2) ** 2, 2 * (x - 2) + 2
x0 = torch.tensor(0.0, requires_grad=True)
x = gd(fcn, x0, [])
x, fcn(x)

(tensor(0.9973), (tensor(3.0000), tensor(-0.0053)))