# How to implement a new TensorGraph layer

In [5]:
import tensorflow as tf
import tensorflow.contrib.eager as tfe

In [9]:
import deepchem as dc
import numpy as np
import random

### Using numpy to create random samples

In [10]:
np.random.seed(2)
data = np.random.random((4, 4))
labels = np.random.random((4,))

In [11]:
from deepchem.data.datasets import NumpyDataset

In [12]:
dataset = NumpyDataset(data, labels)

In [13]:
dataset.X

array([[ 0.4359949 ,  0.02592623,  0.54966248,  0.43532239],
       [ 0.4203678 ,  0.33033482,  0.20464863,  0.61927097],
       [ 0.29965467,  0.26682728,  0.62113383,  0.52914209],
       [ 0.13457995,  0.51357812,  0.18443987,  0.78533515]])

In [14]:
dataset.y

array([[ 0.85397529],
       [ 0.49423684],
       [ 0.84656149],
       [ 0.07964548]])

In [16]:
from deepchem.models.tensorgraph.layers import Dense

In [34]:
from deepchem.models.tensorgraph.layers import Layer

### Declaring the inputs

In [43]:
inputs = tf.constant(dataset.X)
print(inputs)

tf.Tensor(
[[ 0.4359949   0.02592623  0.54966248  0.43532239]
 [ 0.4203678   0.33033482  0.20464863  0.61927097]
 [ 0.29965467  0.26682728  0.62113383  0.52914209]
 [ 0.13457995  0.51357812  0.18443987  0.78533515]], shape=(4, 4), dtype=float64)


### Performing Tensorflow math operation

__tf.add__ implements element-wise addition

In [44]:
custom_layer = tf.add(inputs, 2)
print(custom_layer)

tf.Tensor(
[[ 2.4359949   2.02592623  2.54966248  2.43532239]
 [ 2.4203678   2.33033482  2.20464863  2.61927097]
 [ 2.29965467  2.26682728  2.62113383  2.52914209]
 [ 2.13457995  2.51357812  2.18443987  2.78533515]], shape=(4, 4), dtype=float64)


In [45]:
dense_layer = Dense(4)
print(dense_layer)

### Implementing new layer in Tensorgraph



In [46]:
x = dense_layer.create_tensor(in_layers = [custom_layer], set_tensors=True)
# or you can use
# Dense(4)(inputs)
print(x)

tf.Tensor(
[[-1.05170104  3.37272508 -4.09731314 -2.70992876]
 [-1.52722784  3.34041155 -4.55616791 -3.00043301]
 [-1.01771661  3.25747625 -4.31042888 -2.77546662]
 [-1.63017281  3.08838184 -4.67131372 -2.95020565]], shape=(4, 4), dtype=float64)
